version: 0.0
os: linux
files:
  - source: build.zip
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  Install:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
