version: 0.2

phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install -g @angular/cli
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - echo Build completed on `date`
artifacts:
    files:
        - build/**/*
        - scripts/**/*
        - appspec.yml

#version: 0.2

#phases:
#  pre_build:
#    commands:
#      - echo Instalando dependencias
#      - npm install
#  build:
#    commands:
#      - echo Build da aplicacao iniciado em 'date'
#      - npm run build
#  post_build:
#    commands:
#      - echo Post build em 'date'
#artifacts:
#  files:
#    - build/**/*