version: 0.2
#env:
#    variables:
#        CACHE_CONTROL: "86400"
#        S3_BUCKET: "build.modulo-10"
#        BUILD_FOLDER: "dist/browser"
#        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
#            - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
#            - aws s3 cp dist/browser/. s3://build.modulo-10 --recursive --acl public-read #--cache-control "max-age=${CACHE_CONTROL}"
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/browser'
    discard-paths: yes

#version: 0.2

#phases:
#  pre_build:
#    commands:
#      - echo Instalando dependencias
#      - npm install
#  build:
#    commands:
#      - echo Build da aplicacao iniciado em 'date'
#      - npm run build
#  post_build:
#    commands:
#      - echo Post build em 'date'
#artifacts:
#  files:
#    - build/**/*